package com.example.leavemanagement.policy.application;
import com.example.leavemanagement.audit.persistence.*; import com.example.leavemanagement.policy.persistence.*; import com.example.leavemanagement.shared.api.DomainException; import com.example.leavemanagement.shared.security.CurrentActorProvider; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service @Transactional public class LeavePolicyAdministrationService {
 private final LeaveTypeRepository types; private final LeavePolicyVersionRepository policies; private final AuditEventRepository audits; private final CurrentActorProvider actors;
 public LeavePolicyAdministrationService(LeaveTypeRepository t,LeavePolicyVersionRepository p,AuditEventRepository a,CurrentActorProvider c){types=t;policies=p;audits=a;actors=c;}
 private void admin(){if(!actors.require().hasRole("ADMINISTRATOR"))throw new DomainException(403,"ACCESS_DENIED","Administrator role is required");}
 private void days(Collection<Integer> d){if(d==null||d.stream().anyMatch(x->x==null||x<1||x>7)||d.size()!=new HashSet<>(d).size())throw new DomainException(400,"VALIDATION_FAILED","weeklyOffDays must contain unique ISO days 1 through 7");}
 public List<Detail> list(){admin();return types.findAllByOrderByNameAsc().stream().map(this::detail).toList();}
 public Detail createType(TypeCreate c){admin();if(types.existsByCodeIgnoreCase(c.code()))throw new DomainException(409,"RESOURCE_CONFLICT","Leave type code already exists");var t=types.save(LeaveTypeEntity.create(UUID.randomUUID(),c.code(),c.name(),c.description(),c.active()));audits.save(AuditEventEntity.administration(actors.require().userId(),"LEAVE_TYPE_CREATED","LEAVE_TYPE",t.getId(),null,null,"{\"code\":\""+t.getCode()+"\"}"));return detail(t);}
 public Detail updateType(UUID id,TypeUpdate c){admin();var t=types.findById(id).orElseThrow(()->new DomainException(404,"RESOURCE_NOT_FOUND","Leave type was not found"));if(t.getVersion()!=c.expectedVersion())throw new DomainException(409,"STALE_VERSION","The leave type was changed; reload and retry");t.update(c.code(),c.name(),c.description(),c.active());audits.save(AuditEventEntity.administration(actors.require().userId(),c.active()?"LEAVE_TYPE_UPDATED":"LEAVE_TYPE_DEACTIVATED","LEAVE_TYPE",id,null,null,"{\"active\":"+c.active()+"}"));return detail(t);}
 public PolicyView createPolicy(UUID typeId,PolicyCommand c){admin();days(c.weeklyOffDays());var t=types.findById(typeId).orElseThrow(()->new DomainException(404,"RESOURCE_NOT_FOUND","Leave type was not found"));if(t.getVersion()!=c.expectedVersion())throw new DomainException(409,"STALE_VERSION","The leave type was changed; reload and retry");if(c.effectiveTo()!=null&&c.effectiveTo().isBefore(c.effectiveFrom()))throw new DomainException(400,"VALIDATION_FAILED","effectiveTo must not precede effectiveFrom");var previous=policies.findAllByLeaveTypeIdOrderByVersionNumberDesc(typeId);var n=previous.isEmpty()?1:previous.getFirst().getVersionNumber()+1;var p=policies.save(LeavePolicyVersionEntity.create(UUID.randomUUID(),t,n,c.effectiveFrom(),c.effectiveTo(),c.tracksBalance(),c.allowsHalfDay(),c.weeklyOffTreatment(),c.holidayTreatment(),c.rejectionCommentRequired(),c.cancellationCutoffDays(),c.weeklyOffDays(),Instant.now()));audits.save(AuditEventEntity.administration(actors.require().userId(),"POLICY_VERSION_CREATED","LEAVE_POLICY_VERSION",p.getId(),null,null,"{\"versionNumber\":"+n+"}"));return policy(p);}
 private Detail detail(LeaveTypeEntity t){var ps=policies.findAllByLeaveTypeIdOrderByVersionNumberDesc(t.getId());LeavePolicyVersionEntity p=ps.isEmpty()?null:ps.getFirst();return new Detail(t.getId(),t.getCode(),t.getName(),p==null?false:p.isTracksBalance(),p==null?false:p.isAllowsHalfDay(),p==null?0:p.getCancellationCutoffDays(),t.getDescription(),t.isActive(),p==null?null:policy(p),t.getVersion());}
 private PolicyView policy(LeavePolicyVersionEntity p){return new PolicyView(p.getId(),p.getVersionNumber(),p.getEffectiveFrom(),p.getEffectiveTo(),p.isTracksBalance(),p.isAllowsHalfDay(),p.getWeeklyOffTreatment(),p.getHolidayTreatment(),p.isRejectionCommentRequired(),p.getCancellationCutoffDays(),p.getWeeklyOffDays());}
 public record TypeCreate(String code,String name,String description,boolean active){} public record TypeUpdate(String code,String name,String description,boolean active,long expectedVersion){} public record PolicyCommand(LocalDate effectiveFrom,LocalDate effectiveTo,boolean tracksBalance,boolean allowsHalfDay,String weeklyOffTreatment,String holidayTreatment,boolean rejectionCommentRequired,int cancellationCutoffDays,Collection<Integer> weeklyOffDays,long expectedVersion){} public record Detail(UUID id,String code,String name,boolean tracksBalance,boolean allowsHalfDay,int cancellationCutoffDays,String description,boolean active,PolicyView currentPolicy,long version){} public record PolicyView(UUID id,int versionNumber,LocalDate effectiveFrom,LocalDate effectiveTo,boolean tracksBalance,boolean allowsHalfDay,String weeklyOffTreatment,String holidayTreatment,boolean rejectionCommentRequired,int cancellationCutoffDays,Set<Integer> weeklyOffDays){}
}
