package com.example.leavemanagement.contract;
import com.example.leavemanagement.auth.application.AccountUserDetailsService;
import com.example.leavemanagement.balance.api.EmployeeBalanceController;
import com.example.leavemanagement.balance.application.LeaveBalanceService;
import com.example.leavemanagement.calendar.api.*;
import com.example.leavemanagement.calendar.application.*;
import com.example.leavemanagement.policy.api.LeaveTypeController;
import com.example.leavemanagement.policy.application.LeavePolicyQueryService;
import com.example.leavemanagement.request.api.EmployeeLeaveRequestController;
import com.example.leavemanagement.request.application.*;
import com.example.leavemanagement.request.domain.*;
import com.example.leavemanagement.request.persistence.LeaveRequestEntity;
import com.example.leavemanagement.shared.security.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest;
import org.springframework.context.annotation.Import;
import org.springframework.http.MediaType;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.web.context.SecurityContextRepository;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;
import java.time.LocalDate;
import java.time.Instant;
import java.nio.file.*;
import java.util.*;
import org.yaml.snakeyaml.Yaml;
import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.user;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.csrf;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@WebMvcTest({EmployeeLeaveRequestController.class,EmployeeBalanceController.class,LeaveTypeController.class,HolidayController.class,EmployeeDashboardController.class,EmployeeTeamCalendarController.class}) @Import(SecurityConfiguration.class)
class EmployeeLeaveApiContractTest {
 @Autowired MockMvc mvc;@MockitoBean LeaveCalculationService calculations;@MockitoBean LeaveSubmissionService submissions;@MockitoBean EmployeeLeaveRequestQueryService queries;@MockitoBean LeaveBalanceService balances;@MockitoBean LeavePolicyQueryService policies;@MockitoBean HolidayQueryService holidays;@MockitoBean EmployeeDashboardService dashboards;@MockitoBean EmployeeTeamCalendarService calendars;@MockitoBean CurrentActorProvider actors;@MockitoBean AuthenticationManager manager;@MockitoBean AccountUserDetailsService users;@MockitoBean java.time.Clock clock;
 private final UUID userId=UUID.randomUUID(),employeeId=UUID.randomUUID(),typeId=UUID.randomUUID();
 @BeforeEach void actor(){when(actors.require()).thenReturn(new CurrentActor(userId,employeeId,null,Set.of("EMPLOYEE"),"Viewer"));when(clock.instant()).thenReturn(Instant.parse("2026-08-20T00:00:00Z"));when(clock.getZone()).thenReturn(java.time.ZoneOffset.UTC);}
 @Test void missingCsrfOnCalculationAndSubmissionIsForbiddenWithoutMutation()throws Exception{var body="{\"leaveTypeId\":\""+typeId+"\",\"startDate\":\"2026-09-01\",\"endDate\":\"2026-09-01\",\"durationMode\":\"FULL_DAY\",\"reason\":\"Rest\"}";mvc.perform(post("/api/employee/leave-requests/calculate").with(user(userId.toString()).roles("EMPLOYEE")).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("ACCESS_DENIED"));mvc.perform(post("/api/employee/leave-requests").with(user(userId.toString()).roles("EMPLOYEE")).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isForbidden());verifyNoInteractions(calculations,submissions);}
 @Test void invalidCsrfOnCalculationAndSubmissionIsForbiddenWithoutMutation()throws Exception{var body="{\"leaveTypeId\":\""+typeId+"\",\"startDate\":\"2026-09-01\",\"endDate\":\"2026-09-01\",\"durationMode\":\"FULL_DAY\",\"reason\":\"Rest\"}";mvc.perform(post("/api/employee/leave-requests/calculate").header("X-XSRF-TOKEN","invalid").with(user(userId.toString()).roles("EMPLOYEE")).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("ACCESS_DENIED"));mvc.perform(post("/api/employee/leave-requests").header("X-XSRF-TOKEN","invalid").with(user(userId.toString()).roles("EMPLOYEE")).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isForbidden());verifyNoInteractions(calculations,submissions);}
 @Test void teamCalendarUsesExactPrivacyProjection()throws Exception{when(calendars.entries(eq(employeeId),any(),any())).thenReturn(List.of(new EmployeeTeamCalendarService.Entry("Coworker",LocalDate.of(2026,9,1),LocalDate.of(2026,9,2),"PENDING")));var result=mvc.perform(get("/api/employee/team-calendar?from=2026-09-01&to=2026-09-30").with(user(userId.toString()).roles("EMPLOYEE"))).andExpect(status().isOk()).andExpect(jsonPath("$[0].employeeDisplayName").value("Coworker")).andExpect(jsonPath("$[0].startDate").value("2026-09-01")).andExpect(jsonPath("$[0].endDate").value("2026-09-02")).andExpect(jsonPath("$[0].status").value("PENDING")).andReturn();Map<String,Object> entry=com.jayway.jsonpath.JsonPath.read(result.getResponse().getContentAsString(),"$[0]");assertThat(entry.keySet()).containsExactlyInAnyOrder("employeeDisplayName","startDate","endDate","status");}
 @Test void ownHistoryNeverAcceptsAnEmployeeIdentifier()throws Exception{when(queries.list(employeeId,0,20)).thenReturn(new EmployeeLeaveRequestQueryService.PageView(List.of(),0,20,0,0));mvc.perform(get("/api/employee/leave-requests?page=0&size=20&employeeId="+UUID.randomUUID()).with(user(userId.toString()).roles("EMPLOYEE"))).andExpect(status().isOk());verify(queries).list(employeeId,0,20);}
 @Test void ownHistorySupportsTheOpenApiStatusFilterWithoutAcceptingOwnershipInput()throws Exception{when(queries.list(employeeId,0,20,"PENDING")).thenReturn(new EmployeeLeaveRequestQueryService.PageView(List.of(summary(UUID.randomUUID())),0,20,1,1));mvc.perform(get("/api/employee/leave-requests?status=PENDING&employeeId="+UUID.randomUUID()).with(user(userId.toString()).roles("EMPLOYEE"))).andExpect(status().isOk()).andExpect(jsonPath("$.content[0].status").value("PENDING"));verify(queries).list(employeeId,0,20,"PENDING");}
 @Test void leaveTypesHolidaysAndOwnBalancesFollowTheEmployeeContract()throws Exception{when(policies.activeTypes(any())).thenReturn(List.of(new LeavePolicyQueryService.LeaveTypeSummary(typeId,"ANNUAL","Annual",true,true,1)));when(holidays.list(any(),any())).thenReturn(List.of(new HolidayQueryService.HolidayView(UUID.randomUUID(),LocalDate.of(2026,10,2),"Holiday",true,0)));when(balances.own(employeeId)).thenReturn(List.of(new LeaveBalanceService.BalanceView(UUID.randomUUID(),typeId,"Annual",LocalDate.of(2026,1,1),LocalDate.of(2026,12,31),20,1,2,17,0)));mvc.perform(get("/api/leave-types").with(user(userId.toString()).roles("EMPLOYEE"))).andExpect(status().isOk()).andExpect(jsonPath("$[0].code").value("ANNUAL")).andExpect(jsonPath("$[0].tracksBalance").value(true));mvc.perform(get("/api/holidays?from=2026-09-01&to=2026-12-31").with(user(userId.toString()).roles("EMPLOYEE"))).andExpect(status().isOk()).andExpect(jsonPath("$[0].date").value("2026-10-02"));mvc.perform(get("/api/employee/leave-balances").with(user(userId.toString()).roles("EMPLOYEE"))).andExpect(status().isOk()).andExpect(jsonPath("$[0].availableDays").value(17));verify(balances).own(employeeId);}
 @Test void calculationAndSubmissionUseServerOwnedIdentityAndAuthoritativeResult()throws Exception{var input=new LeaveCalculationService.Input(typeId,LocalDate.of(2026,9,1),LocalDate.of(2026,9,2),DurationMode.FULL_DAY,"Rest");var calculation=new LeaveCalculation(new LeaveUnits(2),List.of(new LeaveCalculation.CalculatedSlot(LocalDate.of(2026,9,1),"AM"),new LeaveCalculation.CalculatedSlot(LocalDate.of(2026,9,1),"PM")),List.of(new LeaveCalculation.ExcludedDate(LocalDate.of(2026,9,2),LeaveCalculation.ExclusionReason.HOLIDAY)));when(calculations.calculate(eq(employeeId),any())).thenReturn(new LeaveCalculationService.CalculationResult(UUID.randomUUID(),true,"{}",calculation,10.0,true));var body="{\"leaveTypeId\":\""+typeId+"\",\"startDate\":\"2026-09-01\",\"endDate\":\"2026-09-02\",\"durationMode\":\"FULL_DAY\",\"reason\":\"Rest\"}";mvc.perform(post("/api/employee/leave-requests/calculate").with(user(userId.toString()).roles("EMPLOYEE")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isOk()).andExpect(jsonPath("$.chargeableDays").value(1)).andExpect(jsonPath("$.excludedDates[0].reason").value("HOLIDAY")).andExpect(jsonPath("$.tracksBalance").value(true));var saved=LeaveRequestEntity.pending(employeeId,typeId,UUID.randomUUID(),input.startDate(),input.endDate(),input.durationMode().name(),2,input.reason(),"{}","key");when(submissions.submit(eq(userId),eq(employeeId),any(),eq("key"))).thenReturn(saved);when(queries.detail(saved)).thenReturn(detail(saved.getId()));mvc.perform(post("/api/employee/leave-requests").with(user(userId.toString()).roles("EMPLOYEE")).with(csrf()).header("Idempotency-Key","key").contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isCreated()).andExpect(jsonPath("$.employeeId").value(employeeId.toString())).andExpect(jsonPath("$.status").value("PENDING"));verify(submissions).submit(eq(userId),eq(employeeId),any(),eq("key"));}
 @Test void ownListDetailAndDashboardExposeContractShapes()throws Exception{var summary=summary(UUID.randomUUID());var detail=detail(summary.id());when(queries.list(employeeId,0,20)).thenReturn(new EmployeeLeaveRequestQueryService.PageView(List.of(summary),0,20,1,1));when(queries.detail(employeeId,summary.id())).thenReturn(detail);when(dashboards.view(employeeId)).thenReturn(new EmployeeDashboardService.Dashboard(List.of(),List.of(summary),List.of(),List.of()));mvc.perform(get("/api/employee/leave-requests").with(user(userId.toString()).roles("EMPLOYEE"))).andExpect(status().isOk()).andExpect(jsonPath("$.content[0].id").value(summary.id().toString()));mvc.perform(get("/api/employee/leave-requests/"+summary.id()).with(user(userId.toString()).roles("EMPLOYEE"))).andExpect(status().isOk()).andExpect(jsonPath("$.reason").value("Rest")).andExpect(jsonPath("$.statusHistory[0].toStatus").value("PENDING"));mvc.perform(get("/api/employee/dashboard").with(user(userId.toString()).roles("EMPLOYEE"))).andExpect(status().isOk()).andExpect(jsonPath("$.pendingRequests[0].status").value("PENDING"));verify(queries).detail(employeeId,summary.id());verify(dashboards).view(employeeId);}
 @Test void employeeOperationsRequireAuthenticationAndEmployeeRole()throws Exception{mvc.perform(get("/api/employee/leave-balances")).andExpect(status().isUnauthorized()).andExpect(jsonPath("$.code").value("AUTHENTICATION_REQUIRED"));mvc.perform(get("/api/employee/leave-balances").with(user("manager").roles("MANAGER"))).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("ACCESS_DENIED"));verifyNoInteractions(balances);}
 @Test void openApiContainsEveryUs1OperationAndResolvableSchemaReference()throws Exception{var source=Files.readString(Path.of("..","specs","001-employee-leave-management","contracts","openapi.yaml"));Map<String,Object> document=new Yaml().load(source);assertThat(document.get("openapi")).isEqualTo("3.1.0");assertThat(source).contains("operationId: listAvailableLeaveTypes","operationId: listCompanyHolidays","operationId: listOwnLeaveBalances","operationId: calculateOwnLeaveRequest","operationId: submitOwnLeaveRequest","operationId: listOwnLeaveRequests","operationId: getOwnLeaveRequest","operationId: getEmployeeDashboard","operationId: getEmployeeTeamCalendar");var components=(Map<?,?>)document.get("components");var schemas=(Map<?,?>)components.get("schemas");var references=java.util.regex.Pattern.compile("#/components/schemas/([A-Za-z0-9]+)").matcher(source);while(references.find())assertThat(schemas.containsKey(references.group(1))).as("schema reference %s",references.group(1)).isTrue();var team=(Map<?,?>)schemas.get("EmployeeTeamCalendarEntry");assertThat(((Map<?,?>)team.get("properties")).keySet().stream().map(String::valueOf).toList()).containsExactlyInAnyOrder("employeeDisplayName","startDate","endDate","status");var fieldError=(Map<?,?>)schemas.get("FieldError");assertThat(((Map<?,?>)fieldError.get("properties")).keySet().stream().map(String::valueOf).toList()).containsExactlyInAnyOrder("field","code","message");var paths=(Map<?,?>)document.get("paths");var calculation=(Map<?,?>)((Map<?,?>)paths.get("/employee/leave-requests/calculate")).get("post");assertThat(((Map<?,?>)calculation.get("responses")).keySet().stream().map(String::valueOf).toList()).contains("200","400","401","403","409","422");}
 private EmployeeLeaveRequestQueryService.Summary summary(UUID id){return new EmployeeLeaveRequestQueryService.Summary(id,employeeId,"Viewer",typeId,"Annual",LocalDate.of(2026,9,1),LocalDate.of(2026,9,1),"FULL_DAY",1,"PENDING",Instant.parse("2026-08-20T00:00:00Z"),0);}
 private EmployeeLeaveRequestQueryService.Detail detail(UUID id){var s=summary(id);return new EmployeeLeaveRequestQueryService.Detail(s.id(),s.employeeId(),s.employeeName(),s.leaveTypeId(),s.leaveTypeName(),s.startDate(),s.endDate(),s.durationMode(),s.chargeableDays(),s.status(),s.submittedAt(),s.version(),"Rest",null,true,null,List.of(new EmployeeLeaveRequestQueryService.HistoryEntry(null,"PENDING","Viewer",null,s.submittedAt())));}
}
