import { render, screen, fireEvent } from '@testing-library/react'
import { http, HttpResponse } from 'msw'
import { MemoryRouter } from 'react-router-dom'
import { expect, it } from 'vitest'
import { server } from '../../test/setup'
import { AdminEmployeesPage } from './AdminEmployeesPage'
import { AdminPoliciesPage } from './AdminPoliciesPage'

const employee = { id: 'e1', employeeNumber: 'E1', displayName: 'Manager', email: 'm@example.com', managerId: null, managerName: null, roles: ['MANAGER'], active: true, version: 0 }
it('requires creation password and offers unique closed roles and manager choices', async () => { server.use(http.get('/api/admin/employees', () => HttpResponse.json({ content: [employee], page: 0, size: 20, totalElements: 1, totalPages: 1 })), http.post('/api/admin/employees', async ({ request }) => { const body = await request.json() as { initialPassword?: string; roles?: string[]; managerId?: string | null }; expect(body.initialPassword).toBe('correct horse battery'); expect(body.roles).toContain('EMPLOYEE'); expect(body.managerId).toBe('e1'); return HttpResponse.json({ ...employee, id: 'e2' }, { status: 201 }) })); render(<MemoryRouter><AdminEmployeesPage /></MemoryRouter>); expect(await screen.findByRole('option', { name: 'Manager' })).toBeInTheDocument(); fireEvent.change(screen.getByRole('combobox', { name: 'Manager' }), { target: { value: 'e1' } }); expect(screen.getByRole('combobox', { name: 'Manager' })).toHaveValue('e1'); fireEvent.change(screen.getByLabelText('Employee number'), { target: { value: 'E2' } }); fireEvent.change(screen.getByLabelText('Display name'), { target: { value: 'Employee' } }); fireEvent.change(screen.getByLabelText('Email'), { target: { value: 'e@example.com' } }); fireEvent.change(screen.getByLabelText('Login'), { target: { value: 'employee' } }); fireEvent.change(screen.getByLabelText('Initial password'), { target: { value: 'correct horse battery' } }); fireEvent.click(screen.getByRole('button', { name: 'Create employee' })); })
it('renders configurable policy and holiday controls', async () => { server.use(http.get('/api/admin/leave-types', () => HttpResponse.json([{ id: 't1', code: 'A', name: 'Annual', tracksBalance: true, allowsHalfDay: true, cancellationCutoffDays: 2, description: null, active: true, currentPolicy: { id: 'p1', versionNumber: 1, effectiveFrom: '2026-01-01', effectiveTo: null, tracksBalance: true, allowsHalfDay: true, weeklyOffTreatment: 'EXCLUDE', holidayTreatment: 'EXCLUDE', rejectionCommentRequired: false, cancellationCutoffDays: 2, weeklyOffDays: [6, 7] }, version: 0 }])), http.get('/api/admin/holidays*', () => HttpResponse.json([{ id: 'h1', date: '2026-12-25', name: 'Holiday', active: true, version: 0 }])), http.get('/api/admin/employees', () => HttpResponse.json({ content: [], page: 0, size: 20, totalElements: 0, totalPages: 0 }))); render(<MemoryRouter><AdminPoliciesPage /></MemoryRouter>); expect(await screen.findByRole('option', { name: 'Annual' })).toBeInTheDocument(); fireEvent.change(screen.getByRole('combobox', { name: 'Policy leave type' }), { target: { value: 't1' } }); expect(screen.getByRole('checkbox', { name: 'Tracks balance' })).toBeChecked(); expect(screen.getByRole('checkbox', { name: 'Allows half-day' })).toBeChecked(); expect(screen.getByText(/weekly offs: 6, 7/)).toBeInTheDocument(); })
it('handles stale configuration responses without exposing credentials', async () => { server.use(http.get('/api/admin/employees', () => HttpResponse.json({ content: [employee], page: 0, size: 20, totalElements: 1, totalPages: 1 })), http.get('/api/auth/csrf', () => HttpResponse.json({ token: 'csrf', headerName: 'X-XSRF-TOKEN' })), http.patch('/api/admin/employees/e1', () => HttpResponse.json({ type: 'about:blank', title: 'Conflict', status: 409, code: 'STALE_VERSION', detail: 'Reload and retry', correlationId: 'test' }, { status: 409 }))); render(<MemoryRouter><AdminEmployeesPage /></MemoryRouter>); expect(await screen.findByRole('heading', { name: 'Employees and managers' })).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Deactivate' })); expect(await screen.findByRole('alert')).toHaveTextContent('Reload and retry'); expect(screen.getByRole('button', { name: 'Try again' })).toBeInTheDocument(); expect(screen.queryByText(/password_hash/i)).not.toBeInTheDocument() })
