import { render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { http, HttpResponse } from 'msw'
import { server } from '../../test/setup'
import { LeaveRequestFormPage } from './LeaveRequestFormPage'
import { LeaveRequestDetailPage, LeaveRequestHistoryPage } from './LeaveRequestHistoryPage'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { expect, it } from 'vitest'
it('previews configured exclusions and enables a valid submission',async()=>{const typeId=crypto.randomUUID();server.use(http.get('/api/leave-types',()=>HttpResponse.json([{id:typeId,code:'ANNUAL',name:'Annual leave',tracksBalance:true,allowsHalfDay:true,cancellationCutoffDays:1}])),http.get('/api/employee/leave-balances',()=>HttpResponse.json([{id:crypto.randomUUID(),leaveTypeId:typeId,leaveTypeName:'Annual leave',periodStart:'2026-01-01',periodEnd:'2026-12-31',entitledDays:20,reservedDays:0,consumedDays:0,availableDays:20,version:0}])),http.get('/api/auth/csrf',()=>HttpResponse.json({token:'csrf',headerName:'X-XSRF-TOKEN'})),http.post('/api/employee/leave-requests/calculate',()=>HttpResponse.json({chargeableDays:1,chargeableDates:['2026-09-01'],excludedDates:[{date:'2026-09-02',reason:'HOLIDAY'}],tracksBalance:true,availableDays:20,canSubmit:true,messages:[]})));render(<LeaveRequestFormPage/>);await screen.findByText('Annual leave');const user=userEvent.setup();await user.type(screen.getByLabelText('Start date'),'2026-09-01');await user.type(screen.getByLabelText('End date'),'2026-09-02');await user.type(screen.getByLabelText('Reason'),'Rest');await user.click(screen.getByRole('button',{name:'Calculate duration'}));expect(await screen.findByText('1 days')).toBeInTheDocument();expect(screen.getByText(/holiday/)).toBeInTheDocument();expect(screen.getByRole('button',{name:'Submit request'})).toBeEnabled()})

it('exposes half-day controls only for leave types that allow them',async()=>{const allowed=crypto.randomUUID(),fullOnly=crypto.randomUUID();server.use(http.get('/api/leave-types',()=>HttpResponse.json([{id:allowed,code:'ANNUAL',name:'Annual',tracksBalance:true,allowsHalfDay:true,cancellationCutoffDays:1},{id:fullOnly,code:'SPECIAL',name:'Special',tracksBalance:false,allowsHalfDay:false,cancellationCutoffDays:0}])),http.get('/api/employee/leave-balances',()=>HttpResponse.json([])));render(<LeaveRequestFormPage/>);const user=userEvent.setup();expect(await screen.findByRole('option',{name:'Morning half'})).toBeInTheDocument();await user.selectOptions(screen.getByLabelText('Leave type'),fullOnly);expect(screen.queryByRole('option',{name:'Morning half'})).not.toBeInTheDocument();expect(screen.getByLabelText('Start date')).toBeRequired();expect(screen.getByLabelText('End date')).toBeRequired();expect(screen.getByLabelText('Reason')).toBeRequired();expect(screen.getByRole('button',{name:'Submit request'})).toBeDisabled()})

it.each([['LEAVE_OVERLAP','The request overlaps active leave'],['INSUFFICIENT_BALANCE','Insufficient unreserved balance']])('shows actionable %s submission problems',async(code,detail)=>{const typeId=crypto.randomUUID();server.use(http.get('/api/leave-types',()=>HttpResponse.json([{id:typeId,code:'ANNUAL',name:'Annual',tracksBalance:true,allowsHalfDay:true,cancellationCutoffDays:1}])),http.get('/api/employee/leave-balances',()=>HttpResponse.json([])),http.get('/api/auth/csrf',()=>HttpResponse.json({token:'csrf',headerName:'X-XSRF-TOKEN'})),http.post('/api/employee/leave-requests/calculate',()=>HttpResponse.json({chargeableDays:1,chargeableDates:['2026-09-01'],excludedDates:[],tracksBalance:true,availableDays:1,canSubmit:true,messages:[]})),http.post('/api/employee/leave-requests',()=>HttpResponse.json({type:'about:blank',title:'Conflict',status:409,code,detail,correlationId:'test-correlation'},{status:409})));render(<LeaveRequestFormPage/>);const user=userEvent.setup();await screen.findByText('Annual');await user.type(screen.getByLabelText('Start date'),'2026-09-01');await user.type(screen.getByLabelText('End date'),'2026-09-01');await user.type(screen.getByLabelText('Reason'),'Rest');await user.click(screen.getByRole('button',{name:'Calculate duration'}));await screen.findByText('1 days');await user.click(screen.getByRole('button',{name:'Submit request'}));expect(await screen.findByText(new RegExp(detail))).toBeInTheDocument()})

it('prevents duplicate submission while the first request is in flight',async()=>{const typeId=crypto.randomUUID();let submissions=0;server.use(http.get('/api/leave-types',()=>HttpResponse.json([{id:typeId,code:'ANNUAL',name:'Annual',tracksBalance:false,allowsHalfDay:false,cancellationCutoffDays:0}])),http.get('/api/employee/leave-balances',()=>HttpResponse.json([])),http.get('/api/auth/csrf',()=>HttpResponse.json({token:'csrf',headerName:'X-XSRF-TOKEN'})),http.post('/api/employee/leave-requests/calculate',()=>HttpResponse.json({chargeableDays:1,chargeableDates:['2026-09-01'],excludedDates:[],tracksBalance:false,canSubmit:true,messages:[]})),http.post('/api/employee/leave-requests',async()=>{submissions++;await new Promise(resolve=>setTimeout(resolve,100));return HttpResponse.json({id:'request-id'})}));render(<LeaveRequestFormPage/>);const user=userEvent.setup();await screen.findByText('Annual');await user.type(screen.getByLabelText('Start date'),'2026-09-01');await user.type(screen.getByLabelText('End date'),'2026-09-01');await user.type(screen.getByLabelText('Reason'),'Rest');await user.click(screen.getByRole('button',{name:'Calculate duration'}));await screen.findByText('1 days');const submit=screen.getByRole('button',{name:'Submit request'});await user.dblClick(submit);expect(screen.getByRole('button',{name:/Submitting/})).toBeDisabled();expect(submissions).toBe(1)})

it('renders request history and private detail status timeline',async()=>{const summary={id:'request-id',employeeId:'employee-id',employeeName:'Viewer',leaveTypeId:'type-id',leaveTypeName:'Annual',startDate:'2026-09-01',endDate:'2026-09-01',durationMode:'FULL_DAY',chargeableDays:1,status:'PENDING',submittedAt:'2026-08-20T00:00:00Z',version:0};server.use(http.get('/api/employee/leave-requests',()=>HttpResponse.json({content:[summary],page:0,size:20,totalElements:1,totalPages:1})),http.get('/api/employee/leave-requests/request-id',()=>HttpResponse.json({...summary,reason:'Family event',decisionComment:null,canCancel:true,cancellationBlockedReason:null,statusHistory:[{fromStatus:null,toStatus:'PENDING',actorDisplayName:'Viewer',comment:null,occurredAt:'2026-08-20T00:00:00Z'}]})));const {unmount}=render(<MemoryRouter><LeaveRequestHistoryPage/></MemoryRouter>);expect(await screen.findByRole('link',{name:'Annual'})).toBeInTheDocument();expect(screen.getByText('PENDING')).toBeInTheDocument();unmount();render(<MemoryRouter initialEntries={['/employee/requests/request-id']}><Routes><Route path="/employee/requests/:id" element={<LeaveRequestDetailPage/>}/></Routes></MemoryRouter>);expect(await screen.findByText('Family event')).toBeInTheDocument();expect(screen.getAllByText('PENDING')).toHaveLength(2);expect(screen.getByRole('heading',{name:'Status history'})).toBeInTheDocument()})
