import { expect, it, vi } from 'vitest'
import { render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { LeaveRequestDetailPage } from './LeaveRequestHistoryPage'
import { http, HttpResponse } from 'msw'
import { server } from '../../test/setup'

const detail=(overrides:Record<string,unknown>={})=>({id:'r1',employeeId:'e1',employeeName:'E',leaveTypeId:'t1',leaveTypeName:'Annual',startDate:'2026-09-01',endDate:'2026-09-01',durationMode:'FULL_DAY',chargeableDays:1,status:'PENDING',submittedAt:'2026-08-20T00:00:00Z',version:2,reason:'x',decisionComment:null,canCancel:true,cancellationBlockedReason:null,statusHistory:[],...overrides})
const renderDetail=()=>render(<MemoryRouter initialEntries={['/employee/requests/r1']}><Routes><Route path="/employee/requests/:id" element={<LeaveRequestDetailPage/>}/></Routes></MemoryRouter>)
it('shows eligibility and submits the loaded expectedVersion',async()=>{let body:unknown;const confirm=vi.spyOn(window,'confirm').mockReturnValue(true);server.use(http.get('/api/employee/leave-requests/r1',()=>HttpResponse.json(detail())),http.get('/api/auth/csrf',()=>HttpResponse.json({token:'csrf'})),http.post('/api/employee/leave-requests/r1/cancel',async({request})=>{body=await request.json();return HttpResponse.json(detail({status:'CANCELLED',version:3,canCancel:false}))}));renderDetail();const user=userEvent.setup();await user.click(await screen.findByRole('button',{name:'Cancel request'}));expect(await screen.findByText('CANCELLED',{exact:true})).toBeInTheDocument();expect(body).toEqual({expectedVersion:2,comment:''});confirm.mockRestore()})
it('hides action and displays cutoff restriction when ineligible',async()=>{server.use(http.get('/api/employee/leave-requests/r1',()=>HttpResponse.json(detail({status:'APPROVED',canCancel:false,cancellationBlockedReason:'The cancellation cutoff has passed'}))));renderDetail();expect(await screen.findByText(/cutoff/i)).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Cancel request'})).not.toBeInTheDocument()})
it('refreshes after a stale-version problem',async()=>{let reads=0;server.use(http.get('/api/employee/leave-requests/r1',()=>HttpResponse.json(detail({version:++reads}))),http.get('/api/auth/csrf',()=>HttpResponse.json({token:'csrf'})),http.post('/api/employee/leave-requests/r1/cancel',()=>HttpResponse.json({code:'STALE_VERSION',detail:'reload',status:409},{status:409})));const confirm=vi.spyOn(window,'confirm').mockReturnValue(true);renderDetail();const user=userEvent.setup();await user.click(await screen.findByRole('button',{name:'Cancel request'}));expect(await screen.findByText(/eligible|cutoff/i)).toBeInTheDocument();expect(reads).toBe(2);confirm.mockRestore()})
