import { BrowserRouter, Navigate, Route, Routes, useLocation } from 'react-router-dom'
import { useAuth } from '../providers/AuthProvider'
import { AppShell } from '../layout/AppShell'
import { Loading } from '../../shared/components/Ui'
import { LoginPage } from '../../features/auth/LoginPage'
import { EmployeeDashboardPage } from '../../features/dashboard/EmployeeDashboardPage'
import { LeaveRequestFormPage } from '../../features/leave-requests/LeaveRequestFormPage'
import { LeaveRequestHistoryPage, LeaveRequestDetailPage } from '../../features/leave-requests/LeaveRequestHistoryPage'
import { EmployeeTeamCalendarPage } from '../../features/calendar/EmployeeTeamCalendarPage'
import { BalancePage, HolidayPage } from '../../features/leave-requests/ReferencePages'
import { ManagerDashboardPage } from '../../features/dashboard/ManagerDashboardPage'
import { ManagerQueuePage } from '../../features/team-approvals/ManagerQueuePage'
import { ManagerRequestDetailPage } from '../../features/team-approvals/ManagerRequestDetailPage'
import { ManagerTeamCalendarPage } from '../../features/calendar/ManagerTeamCalendarPage'
import { AdminDashboardPage } from '../../features/dashboard/AdminDashboardPage'
import { AdminEmployeesPage } from '../../features/admin/AdminEmployeesPage'
import { AdminPoliciesPage } from '../../features/admin/AdminPoliciesPage'
import { AdminHolidaysPage } from '../../features/admin/AdminHolidaysPage'
import { AdminBalancesPage } from '../../features/admin/AdminBalancesPage'
import { AdminLeaveReportsPage } from '../../features/reports/AdminLeaveReportsPage'
import { AdminAuditHistoryPage } from '../../features/reports/AdminAuditHistoryPage'
import type { ReactNode } from 'react'
function Protected(){const auth=useAuth();const location=useLocation();if(auth.loading)return <Loading/>;if(!auth.principal)return <Navigate to="/login" state={{from:location}} replace/>;if(!auth.principal.roles.some(r=>r==='EMPLOYEE'||r==='MANAGER'||r==='ADMINISTRATOR'))return <p role="alert">Leave access is required.</p>;return <AppShell/>}
function AdminOnly({ children }: { children: ReactNode }) { const auth = useAuth(); return auth.principal?.roles.includes('ADMINISTRATOR') ? <>{children}</> : <p role="alert">Administrator access is required.</p> }
export function AppRouter(){return <BrowserRouter><Routes><Route path="/login" element={<LoginPage/>}/><Route element={<Protected/>}><Route path="/employee" element={<EmployeeDashboardPage/>}/><Route path="/employee/request" element={<LeaveRequestFormPage/>}/><Route path="/employee/requests" element={<LeaveRequestHistoryPage/>}/><Route path="/employee/requests/:id" element={<LeaveRequestDetailPage/>}/><Route path="/employee/balances" element={<BalancePage/>}/><Route path="/employee/holidays" element={<HolidayPage/>}/><Route path="/employee/calendar" element={<EmployeeTeamCalendarPage/>}/><Route path="/manager" element={<ManagerDashboardPage/>}/><Route path="/manager/requests" element={<ManagerQueuePage/>}/><Route path="/manager/requests/:id" element={<ManagerRequestDetailPage/>}/><Route path="/manager/calendar" element={<ManagerTeamCalendarPage/>}/><Route path="/admin" element={<AdminOnly><AdminDashboardPage/></AdminOnly>}/><Route path="/admin/employees" element={<AdminOnly><AdminEmployeesPage/></AdminOnly>}/><Route path="/admin/policies" element={<AdminOnly><AdminPoliciesPage/></AdminOnly>}/><Route path="/admin/holidays" element={<AdminOnly><AdminHolidaysPage/></AdminOnly>}/><Route path="/admin/balances" element={<AdminOnly><AdminBalancesPage/></AdminOnly>}/><Route path="/admin/reports" element={<AdminOnly><AdminLeaveReportsPage/></AdminOnly>}/><Route path="/admin/audit" element={<AdminOnly><AdminAuditHistoryPage/></AdminOnly>}/></Route><Route path="*" element={<Navigate to="/employee" replace/>}/></Routes></BrowserRouter>}
