import { useCallback, useEffect, useState } from 'react'
import { getLeaveSummary, getOrganizationLeaveRequests } from './api'
import type { LeaveSummaryReport, OrganizationLeaveRequest, OrganizationLeaveRequestPage } from '../../shared/types/reporting'
import type { LeaveStatus } from '../../shared/types/leave'
import { ApiError } from '../../shared/api/problem'
import { DataTable, Empty, ErrorSummary, Loading, Retry, StatusBadge } from '../../shared/components/Ui'

const statuses: LeaveStatus[] = ['PENDING', 'APPROVED', 'REJECTED', 'CANCELLED']
const isoToday = () => new Date().toISOString().slice(0, 10)
const firstOfMonth = () => { const d = new Date(); d.setDate(1); return d.toISOString().slice(0, 10) }
const message = (error: unknown) => error instanceof ApiError ? error.problem.detail : 'The report could not be loaded.'
function Summary({ report }: { report: LeaveSummaryReport }) { return <div className="grid"><section className="card"><h2>By status</h2><ul>{report.byStatus.map(x => <li key={x.key}>{x.key}: {x.requestCount} requests, {x.chargeableDays} days</li>)}</ul>{report.byStatus.length === 0 && <Empty>No requests in this period.</Empty>}</section><section className="card"><h2>By leave type</h2><ul>{report.byLeaveType.map(x => <li key={x.key}>{x.key}: {x.requestCount} requests, {x.chargeableDays} days</li>)}</ul>{report.byLeaveType.length === 0 && <Empty>No leave types in this period.</Empty>}</section></div> }
function RequestTable({ page, onPage }: { page: OrganizationLeaveRequestPage; onPage(page: number): void }) { return <><DataTable label="Organization leave requests"><thead><tr><th>Employee</th><th>Leave type</th><th>Dates</th><th>Days</th><th>Status</th></tr></thead><tbody>{page.content.map((r: OrganizationLeaveRequest) => <tr key={r.id}><td>{r.employeeName}</td><td>{r.leaveTypeName}</td><td><time dateTime={r.startDate}>{r.startDate}</time> – <time dateTime={r.endDate}>{r.endDate}</time></td><td>{r.chargeableDays}</td><td><StatusBadge status={r.status} /></td></tr>)}</tbody></DataTable>{page.content.length === 0 && <Empty>No organization requests match these filters.</Empty>}<nav aria-label="Organization request pages"><button type="button" disabled={page.page <= 0} onClick={() => onPage(page.page - 1)}>Previous</button><span> Page {page.page + 1} of {Math.max(page.totalPages, 1)} </span><button type="button" disabled={page.page + 1 >= page.totalPages} onClick={() => onPage(page.page + 1)}>Next</button></nav></> }
export function AdminLeaveReportsPage() {
  const [from, setFrom] = useState(firstOfMonth); const [to, setTo] = useState(isoToday); const [status, setStatus] = useState<LeaveStatus | ''>('');
  const [requests, setRequests] = useState<OrganizationLeaveRequestPage>(); const [summary, setSummary] = useState<LeaveSummaryReport>(); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [page, setPage] = useState(0)
  const load = useCallback((nextPage = 0) => { if (!from || !to || from > to) { setError('Choose a valid reporting period.'); setLoading(false); return } setLoading(true); setError(''); const filters = { from, to, ...(status ? { status } : {}) }; void Promise.all([getOrganizationLeaveRequests(filters, nextPage), getLeaveSummary({ from, to })]).then(([r, s]) => { setRequests(r); setSummary(s); setPage(nextPage) }).catch(e => setError(message(e))).finally(() => setLoading(false)) }, [from, status, to])
  useEffect(() => { const timer = window.setTimeout(() => { void load(0) }, 0); return () => window.clearTimeout(timer) }, [load])
  return <><h1>Organization leave reports</h1><form aria-label="Report filters" onSubmit={e => { e.preventDefault(); void load(0) }}><label>From <input type="date" value={from} onChange={e => setFrom(e.target.value)} /></label><label>To <input type="date" value={to} onChange={e => setTo(e.target.value)} /></label><label>Status <select value={status} onChange={e => setStatus(e.target.value as LeaveStatus | '')}><option value="">All statuses</option>{statuses.map(x => <option key={x} value={x}>{x}</option>)}</select></label><button type="submit">Apply filters</button></form>{error ? <><ErrorSummary message={error} /><Retry onRetry={() => { void load(page) }} /></> : loading ? <Loading label="Loading reports" /> : <>{summary && <Summary report={summary} />}{requests && <section className="card"><h2>Organization requests</h2><RequestTable page={requests} onPage={p => { void load(p) }} /></section>}</>}</>
}
