import { useCallback, useEffect, useState } from 'react'
import { getAuditEvents } from './api'
import type { AuditEventPage } from '../../shared/types/reporting'
import { ApiError } from '../../shared/api/problem'
import { DataTable, Empty, ErrorSummary, Loading, Retry } from '../../shared/components/Ui'
const message = (error: unknown) => error instanceof ApiError ? error.problem.detail : 'Audit history could not be loaded.'
export function AdminAuditHistoryPage() {
  const [entityType, setEntityType] = useState(''); const [entityId, setEntityId] = useState(''); const [page, setPage] = useState<AuditEventPage>(); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  const load = useCallback((next = 0) => { setLoading(true); setError(''); void getAuditEvents(next, 20, entityType || undefined, entityId || undefined).then(setPage).catch(e => setError(message(e))).finally(() => setLoading(false)) }, [entityId, entityType])
  useEffect(() => { const timer = window.setTimeout(() => { void load() }, 0); return () => window.clearTimeout(timer) }, [load])
  return <><h1>Audit history</h1><form aria-label="Audit filters" onSubmit={e => { e.preventDefault(); void load(0) }}><label>Entity type <input value={entityType} onChange={e => setEntityType(e.target.value)} /></label><label>Entity ID <input value={entityId} onChange={e => setEntityId(e.target.value)} /></label><button type="submit">Filter audit events</button></form>{error ? <><ErrorSummary message={error} /><Retry onRetry={() => { void load(page?.page ?? 0) }} /></> : loading ? <Loading label="Loading audit history" /> : page && <section className="card"><DataTable label="Immutable audit events"><thead><tr><th>When</th><th>Action</th><th>Entity</th><th>Actor</th><th>Reason</th></tr></thead><tbody>{page.content.map(e => <tr key={e.id}><td><time dateTime={e.occurredAt}>{new Date(e.occurredAt).toLocaleString()}</time></td><td>{e.action}</td><td>{e.entityType} / {e.entityId}</td><td>{e.actorUserId}</td><td>{e.reason ?? '—'}</td></tr>)}</tbody></DataTable>{page.content.length === 0 && <Empty>No audit events match these filters.</Empty>}<nav aria-label="Audit event pages"><button type="button" disabled={page.page <= 0} onClick={() => { void load(page.page - 1) }}>Previous</button><span> Page {page.page + 1} of {Math.max(page.totalPages, 1)} </span><button type="button" disabled={page.page + 1 >= page.totalPages} onClick={() => { void load(page.page + 1) }}>Next</button></nav></section>}</> }
