package com.example.leavemanagement.integration;
import com.example.leavemanagement.auth.persistence.*;import com.example.leavemanagement.audit.persistence.*;import com.example.leavemanagement.people.application.*;import com.example.leavemanagement.people.persistence.*;import com.example.leavemanagement.shared.api.DomainException;import com.example.leavemanagement.shared.security.*;import org.junit.jupiter.api.*;import org.springframework.security.crypto.password.PasswordEncoder;import java.util.*;import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;
class EmployeeAdministrationTest {
 private final EmployeeProfileRepository employees=mock(EmployeeProfileRepository.class); private final UserAccountRepository accounts=mock(UserAccountRepository.class); private final AuditEventRepository audits=mock(AuditEventRepository.class); private final PasswordEncoder encoder=mock(PasswordEncoder.class); private final CurrentActorProvider actors=mock(CurrentActorProvider.class); private final UUID admin=UUID.randomUUID(); private final EmployeeAdministrationService service=new EmployeeAdministrationService(employees,accounts,audits,encoder,actors);
 @BeforeEach void setup(){when(actors.require()).thenReturn(new CurrentActor(admin,UUID.randomUUID(),null,Set.of("ADMINISTRATOR"),"Admin"));when(encoder.encode("correct horse battery" )).thenReturn("{bcrypt}hash");}
 @Test void createsAtomicAccountAndProfileWithoutPlaintext(){when(accounts.findByNormalizedLogin("new@example.com")).thenReturn(Optional.empty());when(employees.existsByEmployeeNumber("E1")).thenReturn(false);when(employees.existsByEmailIgnoreCase("new@example.com")).thenReturn(false);var view=service.create(new EmployeeAdministrationService.CreateCommand("E1","New","new@example.com","new@example.com","correct horse battery",null,List.of("EMPLOYEE"),true));assertThat(view.roles()).containsExactly("EMPLOYEE");verify(accounts).save(argThat(a->a.getPasswordHash().equals("{bcrypt}hash")&&!a.getPasswordHash().contains("correct horse")));verify(employees).save(any());verify(audits).save(any());}
 @Test void rejectsEmptyUnknownAndDuplicateRoles(){for(var roles:List.of(List.<String>of(),List.of("ROOT"),List.of("EMPLOYEE","EMPLOYEE"))){assertThatThrownBy(()->service.create(new EmployeeAdministrationService.CreateCommand("E1","New","new@example.com","new@example.com","correct horse battery",null,roles,true))).isInstanceOf(DomainException.class).hasMessageContaining("roles");}verifyNoInteractions(accounts,employees);}
 @Test void validatesManagerRoleAndActivity(){var account=UserAccountEntity.create(UUID.randomUUID(),"m","m","hash",Set.of("EMPLOYEE"),java.time.Instant.now());var manager=EmployeeProfileEntity.create(UUID.randomUUID(),"M",account,"Manager","m@example.com",null,true,java.time.Instant.now());when(employees.findById(manager.getId())).thenReturn(Optional.of(manager));assertThatThrownBy(()->service.create(new EmployeeAdministrationService.CreateCommand("E1","New","new@example.com","new@example.com","correct horse battery",manager.getId(),List.of("EMPLOYEE"),true))).isInstanceOf(DomainException.class).hasMessageContaining("active and have MANAGER");}
 @Test void staleUpdateMakesNoMutation(){var account=UserAccountEntity.create(UUID.randomUUID(),"old","old","hash",Set.of("EMPLOYEE"),java.time.Instant.now());var e=EmployeeProfileEntity.create(UUID.randomUUID(),"E1",account,"Old","old@example.com",null,true,java.time.Instant.now());when(employees.findLockedById(e.getId())).thenReturn(Optional.of(e));assertThatThrownBy(()->service.update(e.getId(),new EmployeeAdministrationService.UpdateCommand("E1","New","new@example.com","new",null,List.of("EMPLOYEE"),true,3))).isInstanceOf(DomainException.class).hasMessageContaining("changed");verify(employees,never()).save(any());verifyNoInteractions(audits);}
}
