package com.example.leavemanagement.integration;

import com.example.leavemanagement.audit.persistence.*;import com.example.leavemanagement.balance.application.LeaveBalanceService;import com.example.leavemanagement.balance.persistence.*;import com.example.leavemanagement.request.application.*;import com.example.leavemanagement.request.domain.*;import com.example.leavemanagement.request.persistence.*;import com.example.leavemanagement.shared.api.DomainException;import com.example.leavemanagement.shared.security.CurrentActor;import org.junit.jupiter.api.Test;import java.time.*;import java.util.*;import static org.assertj.core.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;

class ExceptionalCorrectionTransactionTest {
 private final UUID employee=UUID.randomUUID(), type=UUID.randomUUID(), policy=UUID.randomUUID(), user=UUID.randomUUID();private final LeaveRequestRepository requests=mock(LeaveRequestRepository.class);private final LeaveRequestBalanceLineRepository lines=mock(LeaveRequestBalanceLineRepository.class);private final LeaveBalanceRepository balances=mock(LeaveBalanceRepository.class);private final LeaveBalanceMovementRepository movements=mock(LeaveBalanceMovementRepository.class);private final LeaveRequestSlotRepository slots=mock(LeaveRequestSlotRepository.class);private final LeaveRequestStatusHistoryRepository history=mock(LeaveRequestStatusHistoryRepository.class);private final AuditEventRepository audits=mock(AuditEventRepository.class);private final LeaveCalculationService calculations=mock(LeaveCalculationService.class);private final LeaveBalanceService balanceService=mock(LeaveBalanceService.class);private final CurrentActor admin=new CurrentActor(user,employee,null,Set.of("ADMINISTRATOR"),"Admin");
 private ExceptionalCorrectionService service(){return new ExceptionalCorrectionService(requests,lines,balances,movements,slots,history,audits,calculations,balanceService);}
 private LeaveRequestEntity rejected(){var r=LeaveRequestEntity.pending(employee,type,policy,LocalDate.of(2026,9,1),LocalDate.of(2026,9,1),"FULL_DAY",2,"reason","{}","key");r.reject(user,"no");return r;}
 private LeaveCalculationService.CalculationResult calculation(){var c=new LeaveCalculation(new LeaveUnits(2),List.of(new LeaveCalculation.CalculatedSlot(LocalDate.of(2026,9,1),"AM"),new LeaveCalculation.CalculatedSlot(LocalDate.of(2026,9,1),"PM")),List.of());return new LeaveCalculationService.CalculationResult(policy,true,"{}",c,4.0,true);}
 @Test void onlyAdministratorMayCorrect(){assertThatThrownBy(()->service().correct(new CurrentActor(UUID.randomUUID(),employee,null,Set.of("EMPLOYEE"),"E"),UUID.randomUUID(),"CANCEL_PENDING","r",0)).isInstanceOf(DomainException.class).extracting("code").isEqualTo("ACCESS_DENIED");verifyNoInteractions(requests,lines,balances,movements,slots,history,audits);}
 @Test void rejectedToPendingRevalidatesThenRecreatesOccupancyAndReservation(){var r=rejected();var balanceId=UUID.randomUUID();var line=LeaveRequestBalanceLineEntity.reserved(r.getId(),balanceId,2);line.release();var oldSlot=LeaveRequestSlotEntity.active(r.getId(),employee,r.getStartDate(),"AM");oldSlot.deactivate();when(requests.lockById(r.getId())).thenReturn(Optional.of(r));when(calculations.calculate(eq(employee),any())).thenReturn(calculation());when(slots.findAllByEmployeeIdAndLeaveDateInAndActiveTrue(eq(employee),any())).thenReturn(List.of());when(lines.findAllByRequestId(r.getId())).thenReturn(new ArrayList<>(List.of(line)));when(balanceService.reserve(eq(employee),eq(type),any())).thenReturn(List.of(new LeaveBalanceService.Reservation(balanceId,2)));when(slots.findAllByRequestId(r.getId())).thenReturn(new ArrayList<>(List.of(oldSlot)));service().correct(admin,r.getId(),"REOPEN_REJECTED","fix",0);assertThat(r.getStatus()).isEqualTo("PENDING");assertThat(line.getState()).isEqualTo("RESERVED");assertThat(oldSlot.isActive()).isTrue();verify(movements).save(any());verify(history).save(any());verify(audits).save(any());}
 @Test void overlapFailureLeavesRejectedRequestAndDoesNotReserve(){var r=rejected();var other=LeaveRequestSlotEntity.active(UUID.randomUUID(),employee,r.getStartDate(),"AM");when(requests.lockById(r.getId())).thenReturn(Optional.of(r));when(calculations.calculate(eq(employee),any())).thenReturn(calculation());when(slots.findAllByEmployeeIdAndLeaveDateInAndActiveTrue(eq(employee),any())).thenReturn(List.of(other));assertThatThrownBy(()->service().correct(admin,r.getId(),"REOPEN_REJECTED","fix",0)).isInstanceOf(DomainException.class).extracting("code").isEqualTo("LEAVE_OVERLAP");assertThat(r.getStatus()).isEqualTo("REJECTED");verifyNoInteractions(balanceService,movements,history,audits);}
 @Test void insufficientBalanceFailureLeavesRejectedRequestUnchanged(){var r=rejected();when(requests.lockById(r.getId())).thenReturn(Optional.of(r));when(calculations.calculate(eq(employee),any())).thenReturn(calculation());when(slots.findAllByEmployeeIdAndLeaveDateInAndActiveTrue(eq(employee),any())).thenReturn(List.of());when(balanceService.reserve(eq(employee),eq(type),any())).thenThrow(new DomainException(409,"INSUFFICIENT_BALANCE","Insufficient unreserved balance"));assertThatThrownBy(()->service().correct(admin,r.getId(),"REOPEN_REJECTED","fix",0)).isInstanceOf(DomainException.class).extracting("code").isEqualTo("INSUFFICIENT_BALANCE");assertThat(r.getStatus()).isEqualTo("REJECTED");verifyNoInteractions(movements,history,audits);}
 @Test void forbiddenAndSameStatusActionsDoNotMutate(){var r=rejected();when(requests.lockById(r.getId())).thenReturn(Optional.of(r));assertThatThrownBy(()->service().correct(admin,r.getId(),"CANCEL_APPROVED","fix",0)).isInstanceOf(DomainException.class).extracting("code").isEqualTo("INVALID_STATUS_TRANSITION");assertThatThrownBy(()->service().correct(admin,r.getId(),"REJECTED","fix",0)).isInstanceOf(DomainException.class).extracting("code").isEqualTo("INVALID_CORRECTION_ACTION");verifyNoInteractions(lines,balances,movements,slots,history,audits);}
}
