package com.example.leavemanagement.integration;

import com.example.leavemanagement.audit.persistence.*;
import com.example.leavemanagement.balance.persistence.*;
import com.example.leavemanagement.policy.application.LeavePolicyQueryService;
import com.example.leavemanagement.policy.persistence.LeavePolicyVersionEntity;
import com.example.leavemanagement.request.application.CancelLeaveRequestService;
import com.example.leavemanagement.request.persistence.*;
import com.example.leavemanagement.shared.api.DomainException;
import com.example.leavemanagement.shared.security.CurrentActor;
import org.junit.jupiter.api.Test;
import java.time.*;import java.util.*;
import static org.assertj.core.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;

class LeaveCancellationTransactionTest {
    private final UUID employee=UUID.randomUUID(), type=UUID.randomUUID(), policyId=UUID.randomUUID(), user=UUID.randomUUID();
    private final LeaveRequestRepository requests=mock(LeaveRequestRepository.class); private final LeaveRequestBalanceLineRepository lines=mock(LeaveRequestBalanceLineRepository.class); private final LeaveBalanceRepository balances=mock(LeaveBalanceRepository.class); private final LeaveBalanceMovementRepository movements=mock(LeaveBalanceMovementRepository.class); private final LeaveRequestSlotRepository slots=mock(LeaveRequestSlotRepository.class); private final LeaveRequestStatusHistoryRepository history=mock(LeaveRequestStatusHistoryRepository.class); private final AuditEventRepository audits=mock(AuditEventRepository.class); private final LeavePolicyQueryService policies=mock(LeavePolicyQueryService.class); private final Clock clock=Clock.fixed(Instant.parse("2026-08-20T00:00:00Z"),ZoneOffset.UTC);
    private final CurrentActor actor=new CurrentActor(user,employee,null,Set.of("EMPLOYEE"),"Employee");
    private CancelLeaveRequestService service(){return new CancelLeaveRequestService(requests,lines,balances,movements,slots,history,audits,policies,clock);}
    private LeavePolicyVersionEntity policy(){var p=mock(LeavePolicyVersionEntity.class);when(p.getId()).thenReturn(policyId);when(p.getCancellationCutoffDays()).thenReturn(1);return p;}
    private LeaveBalanceEntity balance(UUID id){return LeaveBalanceEntity.allocate(id,employee,type,LocalDate.of(2026,1,1),LocalDate.of(2026,12,31),10,Instant.now());}
    @Test void pendingCancellationReleasesReservationAndWritesAllHistory(){var balanceId=UUID.randomUUID();var request=LeaveRequestEntity.pending(employee,type,policyId,LocalDate.of(2026,9,1),LocalDate.of(2026,9,1),"FULL_DAY",2,"reason","{}","key");var line=LeaveRequestBalanceLineEntity.reserved(request.getId(),balanceId,2);var balance=balance(balanceId);balance.reserve(2);var slot=LeaveRequestSlotEntity.active(request.getId(),employee,request.getStartDate(),"AM");var pol=policy();when(requests.lockOwned(request.getId(),employee)).thenReturn(Optional.of(request));when(policies.effective(type,request.getStartDate())).thenReturn(pol);when(lines.findAllByRequestId(request.getId())).thenReturn(List.of(line));when(balances.findLockedById(balanceId)).thenReturn(Optional.of(balance));when(slots.findAllByRequestId(request.getId())).thenReturn(List.of(slot));service().cancel(actor,request.getId(),0,"changed");assertThat(request.getStatus()).isEqualTo("CANCELLED");assertThat(line.getState()).isEqualTo("RELEASED");assertThat(balance.getReservedUnits()).isZero();assertThat(slot.isActive()).isFalse();verify(movements).save(any());verify(history).save(any());verify(audits).save(any());}
    @Test void approvedCancellationRestoresConsumedBalance(){var balanceId=UUID.randomUUID();var request=LeaveRequestEntity.pending(employee,type,policyId,LocalDate.of(2026,9,1),LocalDate.of(2026,9,1),"FULL_DAY",2,"reason","{}","key");request.approve(user,"ok");var line=LeaveRequestBalanceLineEntity.reserved(request.getId(),balanceId,2);line.consume();var balance=balance(balanceId);balance.reserve(2);balance.consumeReserved(2);var pol=policy();when(requests.lockOwned(request.getId(),employee)).thenReturn(Optional.of(request));when(policies.effective(type,request.getStartDate())).thenReturn(pol);when(lines.findAllByRequestId(request.getId())).thenReturn(List.of(line));when(balances.findLockedById(balanceId)).thenReturn(Optional.of(balance));when(slots.findAllByRequestId(request.getId())).thenReturn(List.of());service().cancel(actor,request.getId(),0,null);assertThat(request.getStatus()).isEqualTo("CANCELLED");assertThat(line.getState()).isEqualTo("RESTORED");assertThat(balance.getConsumedUnits()).isZero();}
    @Test void staleVersionDoesNotReadBalanceOrWriteHistory(){var request=LeaveRequestEntity.pending(employee,type,policyId,LocalDate.now(),LocalDate.now(),"FULL_DAY",2,"x","{}","k");when(requests.lockOwned(request.getId(),employee)).thenReturn(Optional.of(request));assertThatThrownBy(()->service().cancel(actor,request.getId(),99,null)).isInstanceOf(DomainException.class).extracting("code").isEqualTo("STALE_VERSION");verifyNoInteractions(lines,balances,movements,slots,history,audits,policies);}
    @Test void secondCancellationWithCurrentStateIsRejectedWithoutMutation(){var request=LeaveRequestEntity.pending(employee,type,policyId,LocalDate.now(),LocalDate.now(),"FULL_DAY",2,"x","{}","k");request.cancel(user,null);var pol=policy();when(requests.lockOwned(request.getId(),employee)).thenReturn(Optional.of(request));when(policies.effective(type,request.getStartDate())).thenReturn(pol);assertThatThrownBy(()->service().cancel(actor,request.getId(),0,null)).isInstanceOf(DomainException.class).extracting("code").isEqualTo("INVALID_STATUS_TRANSITION");verifyNoInteractions(lines,balances,movements,slots,history,audits);}
}
