package com.example.leavemanagement.integration;

import com.example.leavemanagement.request.application.*;
import com.example.leavemanagement.request.domain.DurationMode;
import com.example.leavemanagement.balance.application.*;
import com.example.leavemanagement.shared.security.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import java.sql.Timestamp;import java.time.*;import java.util.*;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.Mockito.when;

@SpringBootTest
class LedgerAuditReconciliationTest extends PostgresIntegrationTest {
 @Autowired JdbcTemplate jdbc;@Autowired LeaveSubmissionService submissions;@Autowired ManagerDecisionService decisions;@Autowired CancelLeaveRequestService cancellations;@Autowired ExceptionalCorrectionService corrections;@Autowired BalanceAllocationService allocations;@Autowired BalanceAdjustmentService adjustments;@MockitoBean CurrentActorProvider actors;private Fixture fixture;
 @BeforeEach void reset(){jdbc.execute("truncate table user_account, leave_type restart identity cascade");jdbc.execute("create or replace function fail_reconciliation_insert() returns trigger language plpgsql as $$ begin raise exception 'injected reconciliation failure'; end $$");fixture=fixture();when(actors.require()).thenReturn(fixture.adminActor());}
 @Test void submitApproveAndEmployeeCancellationReconcileEveryAuthoritativeStore(){var r=submissions.submit(fixture.employeeUser,fixture.employee,input(LocalDate.of(2026,9,1)),"approve-cancel");assertRequest(r.getId(),"PENDING",2,2,0,1);decisions.decide(fixture.managerActor(),r.getId(),0,"approved",true);assertRequest(r.getId(),"APPROVED",2,0,2,2);cancellations.cancel(fixture.employeeActor(),r.getId(),1,"plans changed");assertRequest(r.getId(),"CANCELLED",0,0,0,3);assertThat(jdbc.queryForList("select movement_type from leave_balance_movement where request_id=? order by created_at,id",String.class,r.getId())).containsExactly("RESERVE","CONSUME_RESERVED","RESTORE_CONSUMED");assertThat(jdbc.queryForList("select to_status from leave_request_status_history where request_id=? order by created_at,id",String.class,r.getId())).containsExactly("PENDING","APPROVED","CANCELLED");}
 @Test void rejectReopenAndAdministratorCancellationReserveAndReleaseExactlyOnce(){var r=submissions.submit(fixture.employeeUser,fixture.employee,input(LocalDate.of(2026,9,2)),"reject-reopen");decisions.decide(fixture.managerActor(),r.getId(),0,"not now",false);assertRequest(r.getId(),"REJECTED",0,0,0,2);corrections.correct(fixture.adminActor(),r.getId(),"REOPEN_REJECTED","revalidate",1);assertRequest(r.getId(),"PENDING",2,2,0,3);corrections.correct(fixture.adminActor(),r.getId(),"CANCEL_PENDING","close",2);assertRequest(r.getId(),"CANCELLED",0,0,0,4);assertThat(jdbc.queryForList("select movement_type from leave_balance_movement where request_id=? order by created_at,id",String.class,r.getId())).containsExactly("RESERVE","RELEASE_RESERVED","RESERVE","RELEASE_RESERVED");}
 @Test void administratorApprovedCancellationRestoresConsumptionExactlyOnce(){var r=submissions.submit(fixture.employeeUser,fixture.employee,input(LocalDate.of(2026,9,5)),"admin-cancel-approved");decisions.decide(fixture.managerActor(),r.getId(),0,null,true);corrections.correct(fixture.adminActor(),r.getId(),"CANCEL_APPROVED","exceptional correction",1);assertRequest(r.getId(),"CANCELLED",0,0,0,3);assertThat(jdbc.queryForList("select movement_type from leave_balance_movement where request_id=? order by created_at,id",String.class,r.getId())).containsExactly("RESERVE","CONSUME_RESERVED","RESTORE_CONSUMED");}
 @Test void allocationAndAdjustmentReconcileSummaryLedgerAndAudit(){var type=UUID.randomUUID();jdbc.update("insert into leave_type values (?,?,?,?,?,0)",type,"SPECIAL","Special",null,true);var allocated=allocations.allocate(fixture.employee,new BalanceAllocationService.Command(type,LocalDate.of(2026,1,1),LocalDate.of(2026,12,31),5,"opening"),"allocation-key");var adjusted=adjustments.adjust(allocated.id(),new BalanceAdjustmentService.Command(1,"correction",0),"adjustment-key");assertThat(adjusted.entitledDays()).isEqualTo(6);assertThat(jdbc.queryForList("select movement_type from leave_balance_movement where balance_id=? order by created_at,id",String.class,allocated.id())).containsExactly("ALLOCATE","ADMIN_ADJUST");assertThat(jdbc.queryForObject("select count(*) from audit_event where entity_id=?",Integer.class,allocated.id())).isEqualTo(2);}
 @Test void requiredAuditFailureRollsBackDecisionBalanceOccupancyHistoryAndVersion(){var r=submissions.submit(fixture.employeeUser,fixture.employee,input(LocalDate.of(2026,9,6)),"rollback");var before=snapshot(r.getId());jdbc.execute("create trigger test_fail_audit before insert on audit_event for each row execute function fail_reconciliation_insert()");try{assertThatThrownBy(()->decisions.decide(fixture.managerActor(),r.getId(),0,null,true)).isInstanceOf(RuntimeException.class);}finally{jdbc.execute("drop trigger if exists test_fail_audit on audit_event");}assertThat(snapshot(r.getId())).isEqualTo(before);}
 @Test void staleRetryAndForbiddenCorrectionLeaveDatabaseSnapshotUnchanged(){var r=submissions.submit(fixture.employeeUser,fixture.employee,input(LocalDate.of(2026,9,3)),"stale");decisions.decide(fixture.managerActor(),r.getId(),0,null,true);var before=snapshot(r.getId());assertThatThrownBy(()->decisions.decide(fixture.managerActor(),r.getId(),0,null,true)).hasMessageContaining("changed");assertThat(snapshot(r.getId())).isEqualTo(before);assertThatThrownBy(()->corrections.correct(fixture.adminActor(),r.getId(),"REOPEN_REJECTED","invalid",1)).hasMessageContaining("does not match");assertThat(snapshot(r.getId())).isEqualTo(before);}
 @Test void ledgerStatusHistoryAndAuditRowsAreDatabaseImmutable(){var r=submissions.submit(fixture.employeeUser,fixture.employee,input(LocalDate.of(2026,9,4)),"immutable");for(var table:List.of("leave_balance_movement","leave_request_status_history","audit_event")){var key=table.equals("audit_event")?"entity_id":"request_id";assertThatThrownBy(()->jdbc.update("update "+table+" set id=id where "+key+"=?",r.getId())).isInstanceOf(DataAccessException.class).hasMessageContaining("immutable");assertThatThrownBy(()->jdbc.update("delete from "+table+" where "+key+"=?",r.getId())).isInstanceOf(DataAccessException.class).hasMessageContaining("immutable");}assertRequest(r.getId(),"PENDING",2,2,0,1);}
 private void assertRequest(UUID id,String status,int active,int reserved,int consumed,int events){assertThat(jdbc.queryForObject("select status from leave_request where id=?",String.class,id)).isEqualTo(status);assertThat(jdbc.queryForObject("select count(*) from leave_request_slot where request_id=? and active",Integer.class,id)).isEqualTo(active);assertThat(jdbc.queryForObject("select reserved_units from leave_balance where id=?",Integer.class,fixture.balance)).isEqualTo(reserved);assertThat(jdbc.queryForObject("select consumed_units from leave_balance where id=?",Integer.class,fixture.balance)).isEqualTo(consumed);assertThat(jdbc.queryForObject("select count(*) from leave_balance_movement where request_id=?",Integer.class,id)).isEqualTo(events);assertThat(jdbc.queryForObject("select count(*) from leave_request_status_history where request_id=?",Integer.class,id)).isEqualTo(events);assertThat(jdbc.queryForObject("select count(*) from audit_event where entity_id=?",Integer.class,id)).isEqualTo(events);assertThat(jdbc.queryForObject("select count(*) from leave_request_balance_line where request_id=?",Integer.class,id)).isEqualTo(1);}
 private Snapshot snapshot(UUID id){return new Snapshot(jdbc.queryForObject("select status from leave_request where id=?",String.class,id),jdbc.queryForObject("select version from leave_request where id=?",Long.class,id),jdbc.queryForObject("select reserved_units from leave_balance where id=?",Integer.class,fixture.balance),jdbc.queryForObject("select consumed_units from leave_balance where id=?",Integer.class,fixture.balance),jdbc.queryForObject("select count(*) from leave_balance_movement where request_id=?",Integer.class,id),jdbc.queryForObject("select count(*) from leave_request_status_history where request_id=?",Integer.class,id),jdbc.queryForObject("select count(*) from audit_event where entity_id=?",Integer.class,id),jdbc.queryForObject("select count(*) from leave_request_slot where request_id=? and active",Integer.class,id));}
 private LeaveCalculationService.Input input(LocalDate d){return new LeaveCalculationService.Input(fixture.type,d,d,DurationMode.FULL_DAY,"Rest");}
 private Fixture fixture(){var now=Timestamp.from(Instant.now());var eu=UUID.randomUUID();var mu=UUID.randomUUID();var au=UUID.randomUUID();var e=UUID.randomUUID();var m=UUID.randomUUID();var t=UUID.randomUUID();var p=UUID.randomUUID();var b=UUID.randomUUID();account(eu,"employee","EMPLOYEE",now);account(mu,"manager","MANAGER",now);account(au,"admin","ADMINISTRATOR",now);jdbc.update("insert into employee_profile(id,employee_number,user_account_id,display_name,email,active,created_at,updated_at,version) values (?,?,?,?,?,?,?,?,0)",m,"M1",mu,"Manager","manager@example.com",true,now,now);jdbc.update("insert into employee_profile(id,employee_number,user_account_id,display_name,email,manager_id,active,created_at,updated_at,version) values (?,?,?,?,?,?,?,?,?,0)",e,"E1",eu,"Employee","employee@example.com",m,true,now,now);jdbc.update("insert into leave_type values (?,?,?,?,?,0)",t,"ANNUAL","Annual",null,true);jdbc.update("insert into leave_policy_version values (?,?,?,?,?,?,?,?,?,?,?,?)",p,t,1,LocalDate.of(2026,1,1),null,true,true,"INCLUDE","INCLUDE",false,1,now);jdbc.update("insert into leave_balance(id,employee_id,leave_type_id,period_start,period_end,allocated_units,adjustment_units,reserved_units,consumed_units,version,created_at,updated_at) values (?,?,?,?,?,?,0,0,0,0,?,?)",b,e,t,LocalDate.of(2026,1,1),LocalDate.of(2026,12,31),20,now,now);return new Fixture(eu,mu,au,e,m,t,b);}
 private void account(UUID id,String login,String role,Timestamp now){jdbc.update("insert into user_account values (?,?,?,?,?,?,?,?,?)",id,login,login,"hash",true,now,now,now,0);jdbc.update("insert into user_account_role values (?,?)",id,role);}
 private record Fixture(UUID employeeUser,UUID managerUser,UUID adminUser,UUID employee,UUID manager,UUID type,UUID balance){CurrentActor employeeActor(){return new CurrentActor(employeeUser,employee,manager,Set.of("EMPLOYEE"),"Employee");}CurrentActor managerActor(){return new CurrentActor(managerUser,manager,null,Set.of("MANAGER"),"Manager");}CurrentActor adminActor(){return new CurrentActor(adminUser,manager,null,Set.of("ADMINISTRATOR"),"Admin");}}
 private record Snapshot(String status,long version,int reserved,int consumed,int movements,int history,int audits,int activeSlots){}
}
